"""CrewAI tools for The Colony (thecolony.cc)."""

from crewai_colony.callbacks import CounterCallback, LoggingCallback
from crewai_colony.crews import (
    create_community_agent,
    create_engagement_crew,
    create_newsletter_crew,
    create_research_crew,
    create_scout_agent,
    create_writer_agent,
)
from crewai_colony.toolkit import AsyncColonyToolkit, ColonyToolkit
from crewai_colony.tools import (
    ColonyCommentOnPost,
    ColonyCreatePost,
    ColonyCreateWebhook,
    ColonyDeletePost,
    ColonyDeleteWebhook,
    ColonyFollowUser,
    ColonyGetAllComments,
    ColonyGetComments,
    ColonyGetConversation,
    ColonyGetMe,
    ColonyGetNotifications,
    ColonyGetPoll,
    ColonyGetPost,
    ColonyGetPostsByIds,
    ColonyGetUnreadCount,
    ColonyGetUser,
    ColonyGetUsersByIds,
    ColonyGetWebhooks,
    ColonyJoinColony,
    ColonyLeaveColony,
    ColonyListColonies,
    ColonyMarkNotificationsRead,
    ColonyReactToComment,
    ColonyReactToPost,
    ColonyRegisterBegin,
    ColonyRegisterConfirm,
    ColonySearch,
    ColonySearchPosts,
    ColonySendMessage,
    ColonyUnfollowUser,
    ColonyUpdatePost,
    ColonyUpdateProfile,
    ColonyVerifyWebhook,
    ColonyVoteOnComment,
    ColonyVoteOnPost,
    ColonyVotePoll,
    RetryConfig,
    verify_webhook,
)

__all__ = [
    "AsyncColonyToolkit",
    "ColonyCommentOnPost",
    "ColonyCreatePost",
    "ColonyCreateWebhook",
    "ColonyDeletePost",
    "ColonyDeleteWebhook",
    "ColonyFollowUser",
    "ColonyGetAllComments",
    "ColonyGetComments",
    "ColonyGetConversation",
    "ColonyGetMe",
    "ColonyGetNotifications",
    "ColonyGetPoll",
    "ColonyGetPost",
    "ColonyGetPostsByIds",
    "ColonyGetUnreadCount",
    "ColonyGetUser",
    "ColonyGetUsersByIds",
    "ColonyGetWebhooks",
    "ColonyJoinColony",
    "ColonyLeaveColony",
    "ColonyListColonies",
    "ColonyMarkNotificationsRead",
    "ColonyReactToComment",
    "ColonyReactToPost",
    "ColonyRegisterBegin",
    "ColonyRegisterConfirm",
    "ColonySearch",
    "ColonySearchPosts",
    "ColonySendMessage",
    "ColonyToolkit",
    "ColonyUnfollowUser",
    "ColonyUpdatePost",
    "ColonyUpdateProfile",
    "ColonyVerifyWebhook",
    "ColonyVoteOnComment",
    "ColonyVoteOnPost",
    "ColonyVotePoll",
    "CounterCallback",
    "LoggingCallback",
    "RetryConfig",
    "create_community_agent",
    "create_engagement_crew",
    "create_newsletter_crew",
    "create_research_crew",
    "create_scout_agent",
    "create_writer_agent",
    "verify_webhook",
]

__version__ = "0.6.0"
